-- Part 2: Creation of Snowflake Objects

CREATE DATABASE STUDENT_DB;
USE DATABASE STUDENT_DB;

CREATE SCHEMA STUDENT_SCHEMA;
USE SCHEMA STUDENT_SCHEMA;

CREATE WAREHOUSE STUDENT_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE STUDENT_WH;

CREATE TABLE EMPLOYEE (
    EMP_ID INT,
    EMP_NAME STRING,
    SALARY NUMBER
);

CREATE STAGE EMP_STAGE;

INSERT INTO EMPLOYEE VALUES
(101, 'RAVI', 25000),
(102, 'PRIYA', 30000),
(103, 'ARJUN', 35000);

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE
SET SALARY = 40000
WHERE EMP_ID = 101;

DELETE FROM EMPLOYEE
WHERE EMP_ID = 103;

INSERT INTO EMPLOYEE
VALUES (104, 'KIRAN', 45000);

SELECT * FROM EMPLOYEE
ORDER BY EMP_ID;