-- Part 5: Data Recovery Using Time Travel

-- Identify the row deleted by the DELETE statement:
SELECT * FROM TIME_TRAVEL_DEMO
BEFORE (STATEMENT => '01c7165b-0303-1fc1-001e-87d70014d7da')
MINUS
SELECT * FROM TIME_TRAVEL_DEMO;

-- Recover the missing row:
INSERT INTO TIME_TRAVEL_DEMO (ID, NAME, SALARY)
SELECT ID, NAME, SALARY
FROM TIME_TRAVEL_DEMO
BEFORE (STATEMENT => '01c7165b-0303-1fc1-001e-87d70014d7da')
MINUS
SELECT ID, NAME, SALARY
FROM TIME_TRAVEL_DEMO;

-- Verify recovery:
SELECT * FROM TIME_TRAVEL_DEMO
ORDER BY ID;