-- Part 3: Data Loading Using SnowSQL

CREATE TABLE EMPLOYEE_CSV (
    EMP_ID INT,
    EMP_NAME STRING,
    SALARY NUMBER
);

PUT 'file://C:/Users/HP/telemedicine-nabha/employee_data.csv'
@EMP_STAGE AUTO_COMPRESS=FALSE;

COPY INTO EMPLOYEE_CSV
FROM @EMP_STAGE
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1);

SELECT * FROM EMPLOYEE_CSV
ORDER BY EMP_ID;